[[language]]
name = "arduino"
scope = "source.arduino"
file-types = ["ini"]
roots = []
comment-token = "//"
language-server = {command = "arduino-language-server", args=["-clangd /usr/bin/clangd", "-cli /usr/bin/arduino-cli", "-cli-config $HOME/.arduino15/arduino-cli.yaml"], language-id = "arduino"}

[[language]]
name="cpp"
[language.auto-pairs]
# '<' = '>' 

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock","main.rs"]
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[[language]]
name="asm"
scope = "source.asm"
injection-regex = "asm"
roots = []
file-types = ["asm","nasm","s","S"]
language-server = { command = "asm-lsp"}
comment-token = ";"
indent = {tab-width = 2, unit="  "}
